### ISSUE TITLE
Need help polishing Gitbook

### ISSUE THREAD

**Issue by gaearon** [reactjs/redux#345]
I have Gitbook working in [`rewrite-docs-again`](https://github.com/gaearon/redux/tree/rewrite-docs-again) branch but there are a few rough edges.

* `npm run docs:watch` (launching `gitbook serve`) is extremely slow on changes. Recompiling a book might take 7 seconds. Is that normal, or is something misconfigured?

* When navigating gitbook pages, I see flashes of unstyled content. This is a critical problem. Can we fix them? Does it only happen locally? It doesn't appear like anybody responds to Gitbook issues so I didn't bother filing.

I know Gitbook allows some customization. Maybe veterans can help me out?

cc @theaqua @xgrommx

- [x] Flashes of unstyled content (https://github.com/GitbookIO/gitbook/pull/847)
- [x] Syntax highlighting looks bad especially with JSX (we should use Prism instead of Highlight)
- [x] Add link to edit docs? (#449)
- [x] Cmd+click should open new tab (https://github.com/GitbookIO/gitbook/issues/846, https://github.com/GitbookIO/gitbook/pull/919)
- [x] Remove webfonts (#395, https://github.com/GitbookIO/gitbook/issues/850)
- [ ] Anchor links often don't work the first time (https://github.com/GitbookIO/gitbook/issues/920)
- [ ] Anchors should have permalinks like in React docs (https://github.com/rlmv/gitbook-plugin-anchors)
- [ ] /Dev/ Watches dies for 10 seconds on every second change

**Comment by knowbody** [comment]
looking at it now

**Comment by knowbody** [comment]
@gaearon I don't see the second issue happening on my local (the unstyled content). Everything works ok

**Comment by gaearon** [comment]
@knowbody I see it when switching pages fast in Chrome. But maybe it's my Chrome being weird on beta OS or something.

**Comment by knowbody** [comment]
checked both Chrome and Safari and works fine

**Comment by gaearon** [comment]
That's good to hear!

**Comment by knowbody** [comment]
@gaearon but the build takes a while after the update

**Comment by gaearon** [comment]
If you can help figure out how to make it highlight ES6 syntax, that would help too. Right now the syntax highlighting seems to be ES5-only. For example `import` isn't highlighted.

**Comment by knowbody** [comment]
cool, I'll look into it

**Comment by theaqua** [comment]
* Not 7 seconds, just < 1s
* I also have that weird re-rendering. [I record a demo](https://www.dropbox.com/s/zrxnrjcdcyb0rmv/Untitled.mov?dl=0).

**Comment by gaearon** [comment]
I have about 7 seconds on every second change. First change goes fine, second change hangs. Maybe El Capitan issues (I'm running newest Mac OS beta).

**Comment by theaqua** [comment]
I'm too on OS X El Capitan.

**Comment by knowbody** [comment]
it worked fine for a while now I get this glitching as well

**Comment by knowbody** [comment]
found this: http://ramnathv.github.io/example/
and it seems like it has some kind of spinner, but is it prod only?

**Comment by theaqua** [comment]
About re-rendering. I see, gitbook re-renders entire page (`<head>` too) on every page change. It's not good and I think it's reason why we see that flash blink.

**Comment by theaqua** [comment]
@knowbody maybe plugin?

**Comment by knowbody** [comment]
@theaqua yeah maybe

@gaearon I think the slowness is caused by the way the `gitbook-plugin-livereload` works. It looks more like a quick hack than a plugin. Regarding the highlighting. The owner of GitBook repo said [here](https://github.com/GitbookIO/gitbook/issues/433#issuecomment-54535350) they are using highlight.js
but it seems like highlight.js has a support for ES6 (see [here](https://highlightjs.org/static/demo)) but it seems like the version is outdated (see [here](https://github.com/GitbookIO/gitbook/blob/13fb949d6818bc47a2215ee788c392fa38e1e1d6/package.json)). If you update it to [8.7](https://github.com/isagalaev/highlight.js/releases/tag/8.7) you should be good to go

**Comment by gaearon** [comment]
@knowbody Any idea how to update highlight? Do we need to fork Gitbook? How to install a fork?

**Comment by knowbody** [comment]
@gaearon yeah, I think forking it will be quicker than waiting for the PR to be accepted. How to: http://debuggable.com/posts/how-to-fork-patch-npm-modules:4e2eb9f3-e584-44be-b1a9-3db7cbdd56cb

**Comment by knowbody** [comment]
I'll do it

**Comment by gaearon** [comment]
@knowbody Can you please fork Gitbook, make necessary changes, and then somehow make this branch use your fork?

**Comment by knowbody** [comment]
on it :+1:

**Comment by knowbody** [comment]
no, the latest version is using 8.6 (https://github.com/GitbookIO/gitbook/commit/2f5e53da5581daf01570d422d55dcbc94443fc85), don't know then...

**Comment by knowbody** [comment]
@gaearon I'll try to fix that this evening. I'll get back to you

**Comment by wmertens** [comment]
Or of course give up and use antwar or gatsby instead ;-)

On Tue, Jul 28, 2015, 18:11 Mateusz Zatorski <notifications@github.com>
wrote:

> @gaearon <https://github.com/gaearon> I'll try to fix that this evening.
> I'll get back to you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaearon/redux/issues/345#issuecomment-125666076>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by gaearon** [comment]
Other than dev experience it seems really great.

**Comment by knowbody** [comment]
**highlighting**:
here is what is happening: update to the current `highlight.js` version (8.6) has been made in Gitbook repo, but there was no new release with it. so the current Gitbook release (2.1.0) does not include the newest vesrion of `highlight.js`.

*Hacky solution*:
The solution I found is to use [gitbook-cli to manage Gitbook version](https://github.com/GitbookIO/gitbook-cli#manage-versions). So you clone Gitbook to you local and then you can use it:

1. Remove `_book` directory first
2. `gitbook versions` to check the current installed versions
3. Uninstall all of the installed versions `gitbook versions:uninstall [version]`
4. Link to the cloned Gitbook version `gitbook versions:link 2.1.1-alpha [pathToClonedGitbook]`
5. Check if the installed version is the linked one `gitbook versions`
6. `npm run docs:watch`

And you get the ES6 highlighting:
<img width="1276" alt="screen shot 2015-07-28 at 22 13 00" src="https://cloud.githubusercontent.com/assets/3802023/8944713/1b25ecdc-357a-11e5-90f2-c8f94af74af4.png">

**Comment by theaqua** [comment]
I also submitted an issue about glitches.
https://github.com/GitbookIO/gitbook/issues/838

**Comment by knowbody** [comment]
so now you can just get newest Gitbook @gaearon https://github.com/GitbookIO/gitbook/issues/837#event-367772012

**Comment by AaronO** [comment]
@gaearon @theaqua @knowbody Just so you guys know we love Pull Requests.

Especially if they are fixes, we can merge them quickly, non obvious feature request or breaking changes might require more consideration on our side but if it makes sense we try to move fast and we love getting the community's input.

Let us know if we can help !

**Comment by knowbody** [comment]
awesome! thanks @AaronO

**Comment by gaearon** [comment]
I wish somebody helped me figure out why the third code sample doesn't highlight on this page: http://gaearon.github.io/redux/docs/introduction/ThreePrinciples.html

Evidently it fails only when I use `state = []` default argument syntax. Bug in Highlight.js? Is it fixed yet?

**Comment by AaronO** [comment]
@gaearon Can you point me to the source of that file ? It might be a bug in highlight.js

**Comment by gaearon** [comment]
@AaronO Do you mean markdown source? https://github.com/gaearon/redux/blob/rewrite-docs-again/docs/introduction/ThreePrinciples.md

**Comment by gaearon** [comment]
It probably is a bug. If you change default arg to a number, it'll work. But parsing breaks on string or array.

**Comment by AaronO** [comment]
@gaearon Ok I saw that branch but I assumed it wasn't up to date since it was missing a `SUMMARY.md`.

Do you have `gitbook` version `2.2.0` (which switched to `highlight.js` `8.6`) ?

According to their [changelog](https://github.com/isagalaev/highlight.js/blob/master/CHANGES.md#version-85) there were some JS related fixes in `8.5`.

**Comment by gaearon** [comment]
@AaronO It's in the root: https://github.com/gaearon/redux/blob/rewrite-docs-again/SUMMARY.md. Should I move it somewhere?

Yes, I'm using 2.2.0. @strml is taking a look and says they have this problem in master too. He'll try to figure it out.

**Comment by AaronO** [comment]
@gaearon The bug is indeed in `highlight.js` I tried it on their latest releas `8.7.0` and it doesn't highlight.

Running this code (assuming the code of that snippet is in a file called `code.js`): 

```
require('highlight.js').highlight('js', fs.readFileSync('code.js', 'utf8')).value
```

You will see that it won't highlight anything if you use ES6's default arguments, but if you remove `state = 'SHOW_ALL` and `state = []` then it works.

So this is definitely a bug with `highlight.js` 's ES6 support, we should probably file a bug [there](https://github.com/isagalaev/highlight.js)

**Comment by STRML** [comment]
I've fixed the bug, going to make a PR. Very simple - they simply assumed invalid characters in function params that are no longer invalid in ES6.

**Comment by gaearon** [comment]
Awesome! Thanks!

**Comment by STRML** [comment]
PR is in.

**Comment by knowbody** [comment]
hey @gaearon I've just seen [this](https://github.com/gaearon/redux/issues/383). maybe this could be a hack to solve the loading part

**Comment by peteruithoven** [comment]
If this is still something you guys want, maybe you can add edit links with the following plugin: 
https://www.npmjs.com/package/gitbook-plugin-edit-link

**Comment by jnorthr** [comment]
My gitbok editor WAS showing side-by-side editor and preview but i musthave clicked something that turned it off. Now i only get the editor. Where is the re-enable buton pls ?

**Comment by gaearon** [comment]
@jnorthr Not sure what you are referring to.

**Comment by gaearon** [comment]
Most of these are now solved, except for anchor headers. If anybody wants to help, please let us know!

**Comment by AaronO** [comment]
@gaearon There's a plugin that might do what you want: https://plugins.gitbook.com/plugin/anchors-wrapper

**Comment by gaearon** [comment]
@AaronO 

Thanks, that's exactly what I wanted!
I'll give it a go soon (unless somebody beats me to it with a pull request).

**Comment by gaearon** [comment]
(Actually, https://plugins.gitbook.com/plugin/anchors is the correct one; the other one is broken on NPM and doesn't appear to have any changes in functionality.)

**Comment by jnorthr** [comment]
Sorry Dan, as i do not have npm tool cannot try anchors. Is there another way i can get it on my MacOSX ? Thx jim

**Comment by markerikson** [comment]
Would be nice to figure out the anchor functionality now that I have the FAQ page in.  The other annoyance is that Github by default generates mile-long anchors for headings, basically slug-ifying the entire text of the heading.  Since I've got full questions as my headings, that results in unreadably-long anchors.

I was able to add no-text anchors to my local branch (such as `<a id="performance-scaling">`, and they work fine for clicking the TOC links I've added at the top, but what I'd _really_ like to do is be able to hand out those short links and have people be able to go directly to the question.

Anyone have any updated thoughts on how to approach this?

**Comment by gaearon** [comment]
Aren’t anchors still half-broken in Gitbook? https://github.com/GitbookIO/gitbook/issues/920

**Comment by gaearon** [comment]
Oh wait, nevermind. I see that you read the issue. I’m  ¯\_(ツ)_/¯  on this right now—if you see a good solution, feel free to go ahead with it.

**Comment by markerikson** [comment]
Hmm.  Okay.  The last comment on that Gitbook issue links to a plugin that tries to solve this by adding a short setTimeout to a "page:change" event and re-assigning the hash to the location.  Would adding that plugin be acceptable if it actually does work, or are you against pulling in another plugin?

**Comment by markerikson** [comment]
I just pulled down https://github.com/sifue/gitbook-plugin-anker-enable and rebuilt my local docs.  It does actually work.  It's still a hack, and the behavior isn't perfect (you get a jump to the right anchor, a flash-jump up to the top, and a final jump back to the requested anchor), but it *does* leave you at the right spot if you pasted in a URL with a hash anchor.

@gaearon , you okay with me adding the entry to book.json?

**Comment by gaearon** [comment]
I guess it’s still better than nothing. :+1:

**Comment by markerikson** [comment]
Cool.  In that case, I'll put the TOC branch up for PR here in a couple minutes.

Also, I'm still actually having trouble building the docs properly here on my box.  The double-curly-brace uses in ExampleTodoList.md and UsageWithReact.md keep failing unless I insert a space between the left curlies (ie, `style={{` changed to `style={ {`).  https://github.com/GitbookIO/gitbook/issues/996 seems sorta relevant, but I'm confused why I'm seeing this issue and presumably no one else is.

I've been working around it by keeping modified versions of those two files in my working copy with the extra spaces added, which is not exactly ideal, but allowed me to work on the docs and check the rest of the output.

**Comment by markerikson** [comment]
PR up at #1571.

**Comment by markerikson** [comment]
PR up at #1571.

**Comment by gaearon** [comment]
On an unrelated note, this is quite ugly:

<img width="177" alt="screen shot 2016-04-05 at 19 46 44" src="https://cloud.githubusercontent.com/assets/810438/14294073/3a695eae-fb67-11e5-8562-9184189b87ff.png">

I thought it was sans serif at some point. We should fix it.

**Comment by timdorr** [comment]
Looks like the original issues are taken care of now. We've got some good issues about specific documentation needs, so I'll close this out in favor of those.
